services:
  java-app:
    container_name: java-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: java-app:latest
    restart: unless-stopped
    init: true
    env_file: ./.env # Uncomment if .env file exists
    environment:
      # These are required for the app to connect to the database and for dev convenience
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: skilllink_db
      DB_USER: root
      # DB_PASSWORD should be set via .env or secrets, not in compose
      # JWT_SECRET, EMAIL_HOST, etc. should be set via .env or secrets
    ports:
      - '8080:8080' # Expose Spring Boot default port
    depends_on:
      - mysql-db
    networks:
      - app-network

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: skilllink_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      # Use UTF-8 for full Unicode support
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - '3306:3306' # Expose MySQL default port
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    # Persistent storage for MySQL database
