CREATE TABLE countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    iso2 CHAR(2),
    iso3 CHAR(3),
    phone_code VARCHAR(10)
);

INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Afganistán', 'Afghanistan', 'AF', 'AFG', '93');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Albania', 'Albania', 'AL', 'ALB', '355');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Alemania', 'Germany', 'DE', 'DEU', '49');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Andorra', 'Andorra', 'AD', 'AND', '376');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Angola', 'Angola', 'AO', 'AGO', '244');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Anguila', 'Anguilla', 'AI', 'AIA', '1 264');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Antártida', 'Antarctica', 'AQ', 'ATA', '672');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Antigua y Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', '1 268');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Arabia Saudita', 'Saudi Arabia', 'SA', 'SAU', '966');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Argelia', 'Algeria', 'DZ', 'DZA', '213');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Argentina', 'Argentina', 'AR', 'ARG', '54');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Armenia', 'Armenia', 'AM', 'ARM', '374');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Aruba', 'Aruba', 'AW', 'ABW', '297');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Australia', 'Australia', 'AU', 'AUS', '61');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Austria', 'Austria', 'AT', 'AUT', '43');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Azerbaiyán', 'Azerbaijan', 'AZ', 'AZE', '994');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bélgica', 'Belgium', 'BE', 'BEL', '32');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bahamas', 'Bahamas', 'BS', 'BHS', '1 242');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bahrein', 'Bahrain', 'BH', 'BHR', '973');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bangladesh', 'Bangladesh', 'BD', 'BGD', '880');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Barbados', 'Barbados', 'BB', 'BRB', '1 246');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Belice', 'Belize', 'BZ', 'BLZ', '501');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Benín', 'Benin', 'BJ', 'BEN', '229');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bhután', 'Bhutan', 'BT', 'BTN', '975');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bielorrusia', 'Belarus', 'BY', 'BLR', '375');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Birmania', 'Myanmar', 'MM', 'MMR', '95');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bolivia', 'Bolivia', 'BO', 'BOL', '591');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bosnia y Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', '387');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Botsuana', 'Botswana', 'BW', 'BWA', '267');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Brasil', 'Brazil', 'BR', 'BRA', '55');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Brunéi', 'Brunei', 'BN', 'BRN', '673');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Bulgaria', 'Bulgaria', 'BG', 'BGR', '359');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '226');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Burundi', 'Burundi', 'BI', 'BDI', '257');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Cabo Verde', 'Cape Verde', 'CV', 'CPV', '238');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Camboya', 'Cambodia', 'KH', 'KHM', '855');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Camerún', 'Cameroon', 'CM', 'CMR', '237');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Canadá', 'Canada', 'CA', 'CAN', '1');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Chad', 'Chad', 'TD', 'TCD', '235');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Chile', 'Chile', 'CL', 'CHL', '56');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('China', 'China', 'CN', 'CHN', '86');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Chipre', 'Cyprus', 'CY', 'CYP', '357');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Ciudad del Vaticano', 'Vatican City State', 'VA', 'VAT', '39');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Colombia', 'Colombia', 'CO', 'COL', '57');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Comoras', 'Comoros', 'KM', 'COM', '269');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República del Congo', 'Republic of the Congo', 'CG', 'COG', '242');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República Democrática del Congo', 'Democratic Republic of the Congo', 'CD', 'COD', '243');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Corea del Norte', 'North Korea', 'KP', 'PRK', '850');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Corea del Sur', 'South Korea', 'KR', 'KOR', '82');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Costa de Marfil', 'Ivory Coast', 'CI', 'CIV', '225');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Costa Rica', 'Costa Rica', 'CR', 'CRI', '506');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Croacia', 'Croatia', 'HR', 'HRV', '385');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Cuba', 'Cuba', 'CU', 'CUB', '53');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Curazao', 'Curaçao', 'CW', 'CWU', '5999');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Dinamarca', 'Denmark', 'DK', 'DNK', '45');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Dominica', 'Dominica', 'DM', 'DMA', '1 767');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Ecuador', 'Ecuador', 'EC', 'ECU', '593');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Egipto', 'Egypt', 'EG', 'EGY', '20');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('El Salvador', 'El Salvador', 'SV', 'SLV', '503');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Emiratos Árabes Unidos', 'United Arab Emirates', 'AE', 'ARE', '971');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Eritrea', 'Eritrea', 'ER', 'ERI', '291');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Eslovaquia', 'Slovakia', 'SK', 'SVK', '421');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Eslovenia', 'Slovenia', 'SI', 'SVN', '386');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('España', 'Spain', 'ES', 'ESP', '34');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Estados Unidos de América', 'United States of America', 'US', 'USA', '1');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Estonia', 'Estonia', 'EE', 'EST', '372');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Etiopía', 'Ethiopia', 'ET', 'ETH', '251');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Filipinas', 'Philippines', 'PH', 'PHL', '63');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Finlandia', 'Finland', 'FI', 'FIN', '358');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Fiyi', 'Fiji', 'FJ', 'FJI', '679');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Francia', 'France', 'FR', 'FRA', '33');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Gabón', 'Gabon', 'GA', 'GAB', '241');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Gambia', 'Gambia', 'GM', 'GMB', '220');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Georgia', 'Georgia', 'GE', 'GEO', '995');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Ghana', 'Ghana', 'GH', 'GHA', '233');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Gibraltar', 'Gibraltar', 'GI', 'GIB', '350');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Granada', 'Grenada', 'GD', 'GRD', '1 473');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Grecia', 'Greece', 'GR', 'GRC', '30');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Groenlandia', 'Greenland', 'GL', 'GRL', '299');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guadalupe', 'Guadeloupe', 'GP', 'GLP', '590');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guam', 'Guam', 'GU', 'GUM', '1 671');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guatemala', 'Guatemala', 'GT', 'GTM', '502');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guayana Francesa', 'French Guiana', 'GF', 'GUF', '594');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guernsey', 'Guernsey', 'GG', 'GGY', '44');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guinea', 'Guinea', 'GN', 'GIN', '224');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guinea Ecuatorial', 'Equatorial Guinea', 'GQ', 'GNQ', '240');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guinea-Bissau', 'Guinea-Bissau', 'GW', 'GNB', '245');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Guyana', 'Guyana', 'GY', 'GUY', '592');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Haití', 'Haiti', 'HT', 'HTI', '509');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Honduras', 'Honduras', 'HN', 'HND', '504');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Hong kong', 'Hong Kong', 'HK', 'HKG', '852');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Hungría', 'Hungary', 'HU', 'HUN', '36');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('India', 'India', 'IN', 'IND', '91');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Indonesia', 'Indonesia', 'ID', 'IDN', '62');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Irán', 'Iran', 'IR', 'IRN', '98');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Irak', 'Iraq', 'IQ', 'IRQ', '964');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Irlanda', 'Ireland', 'IE', 'IRL', '353');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Isla Bouvet', 'Bouvet Island', 'BV', 'BVT', 'nan');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Isla de Man', 'Isle of Man', 'IM', 'IMN', '44');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Isla de Navidad', 'Christmas Island', 'CX', 'CXR', '61');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Isla Norfolk', 'Norfolk Island', 'NF', 'NFK', '672');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islandia', 'Iceland', 'IS', 'ISL', '354');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Bermudas', 'Bermuda Islands', 'BM', 'BMU', '1 441');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Caimán', 'Cayman Islands', 'KY', 'CYM', '1 345');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Cocos (Keeling)', 'Cocos (Keeling) Islands', 'CC', 'CCK', '61');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Cook', 'Cook Islands', 'CK', 'COK', '682');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas de Åland', 'Åland Islands', 'AX', 'ALA', '358');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Feroe', 'Faroe Islands', 'FO', 'FRO', '298');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Georgias del Sur y Sandwich del Sur', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Heard y McDonald', 'Heard Island and McDonald Islands', 'HM', 'HMD', 'nan');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Maldivas', 'Maldives', 'MV', 'MDV', '960');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Malvinas', 'Falkland Islands (Malvinas)', 'FK', 'FLK', '500');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Marianas del Norte', 'Northern Mariana Islands', 'MP', 'MNP', '1 670');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Marshall', 'Marshall Islands', 'MH', 'MHL', '692');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Pitcairn', 'Pitcairn Islands', 'PN', 'PCN', '870');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Salomón', 'Solomon Islands', 'SB', 'SLB', '677');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Turcas y Caicos', 'Turks and Caicos Islands', 'TC', 'TCA', '1 649');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Ultramarinas Menores de Estados Unidos', 'United States Minor Outlying Islands', 'UM', 'UMI', '246');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Vírgenes Británicas', 'Virgin Islands', 'VG', 'VGB', '1 284');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Islas Vírgenes de los Estados Unidos', 'United States Virgin Islands', 'VI', 'VIR', '1 340');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Israel', 'Israel', 'IL', 'ISR', '972');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Italia', 'Italy', 'IT', 'ITA', '39');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Jamaica', 'Jamaica', 'JM', 'JAM', '1 876');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Japón', 'Japan', 'JP', 'JPN', '81');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Jersey', 'Jersey', 'JE', 'JEY', '44');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Jordania', 'Jordan', 'JO', 'JOR', '962');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Kazajistán', 'Kazakhstan', 'KZ', 'KAZ', '7');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Kenia', 'Kenya', 'KE', 'KEN', '254');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Kirguistán', 'Kyrgyzstan', 'KG', 'KGZ', '996');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Kiribati', 'Kiribati', 'KI', 'KIR', '686');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Kuwait', 'Kuwait', 'KW', 'KWT', '965');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Líbano', 'Lebanon', 'LB', 'LBN', '961');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Laos', 'Laos', 'LA', 'LAO', '856');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Lesoto', 'Lesotho', 'LS', 'LSO', '266');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Letonia', 'Latvia', 'LV', 'LVA', '371');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Liberia', 'Liberia', 'LR', 'LBR', '231');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Libia', 'Libya', 'LY', 'LBY', '218');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Liechtenstein', 'Liechtenstein', 'LI', 'LIE', '423');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Lituania', 'Lithuania', 'LT', 'LTU', '370');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Luxemburgo', 'Luxembourg', 'LU', 'LUX', '352');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('México', 'Mexico', 'MX', 'MEX', '52');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mónaco', 'Monaco', 'MC', 'MCO', '377');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Macao', 'Macao', 'MO', 'MAC', '853');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Macedônia', 'Macedonia', 'MK', 'MKD', '389');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Madagascar', 'Madagascar', 'MG', 'MDG', '261');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Malasia', 'Malaysia', 'MY', 'MYS', '60');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Malawi', 'Malawi', 'MW', 'MWI', '265');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mali', 'Mali', 'ML', 'MLI', '223');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Malta', 'Malta', 'MT', 'MLT', '356');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Marruecos', 'Morocco', 'MA', 'MAR', '212');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Martinica', 'Martinique', 'MQ', 'MTQ', '596');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mauricio', 'Mauritius', 'MU', 'MUS', '230');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mauritania', 'Mauritania', 'MR', 'MRT', '222');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mayotte', 'Mayotte', 'YT', 'MYT', '262');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Micronesia', 'Estados Federados de', 'FM', 'FSM', '691');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Moldavia', 'Moldova', 'MD', 'MDA', '373');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mongolia', 'Mongolia', 'MN', 'MNG', '976');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Montenegro', 'Montenegro', 'ME', 'MNE', '382');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Montserrat', 'Montserrat', 'MS', 'MSR', '1 664');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Mozambique', 'Mozambique', 'MZ', 'MOZ', '258');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Namibia', 'Namibia', '', 'NAM', '264');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nauru', 'Nauru', 'NR', 'NRU', '674');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nepal', 'Nepal', 'NP', 'NPL', '977');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nicaragua', 'Nicaragua', 'NI', 'NIC', '505');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Niger', 'Niger', 'NE', 'NER', '227');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nigeria', 'Nigeria', 'NG', 'NGA', '234');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Niue', 'Niue', 'NU', 'NIU', '683');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Noruega', 'Norway', 'NO', 'NOR', '47');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nueva Caledonia', 'New Caledonia', 'NC', 'NCL', '687');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Nueva Zelanda', 'New Zealand', 'NZ', 'NZL', '64');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Omán', 'Oman', 'OM', 'OMN', '968');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Países Bajos', 'Netherlands', 'NL', 'NLD', '31');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Pakistán', 'Pakistan', 'PK', 'PAK', '92');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Palau', 'Palau', 'PW', 'PLW', '680');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Palestina', 'Palestine', 'PS', 'PSE', '970');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Panamá', 'Panama', 'PA', 'PAN', '507');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Papúa Nueva Guinea', 'Papua New Guinea', 'PG', 'PNG', '675');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Paraguay', 'Paraguay', 'PY', 'PRY', '595');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Perú', 'Peru', 'PE', 'PER', '51');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Polinesia Francesa', 'French Polynesia', 'PF', 'PYF', '689');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Polonia', 'Poland', 'PL', 'POL', '48');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Portugal', 'Portugal', 'PT', 'PRT', '351');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Puerto Rico', 'Puerto Rico', 'PR', 'PRI', '1');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Qatar', 'Qatar', 'QA', 'QAT', '974');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Reino Unido', 'United Kingdom', 'GB', 'GBR', '44');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República Centroafricana', 'Central African Republic', 'CF', 'CAF', '236');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República Checa', 'Czech Republic', 'CZ', 'CZE', '420');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República Dominicana', 'Dominican Republic', 'DO', 'DOM', '1 809');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('República de Sudán del Sur', 'South Sudan', 'SS', 'SSD', '211');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Reunión', 'Réunion', 'RE', 'REU', '262');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Ruanda', 'Rwanda', 'RW', 'RWA', '250');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Rumanía', 'Romania', 'RO', 'ROU', '40');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Rusia', 'Russia', 'RU', 'RUS', '7');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sahara Occidental', 'Western Sahara', 'EH', 'ESH', '212');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Samoa', 'Samoa', 'WS', 'WSM', '685');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Samoa Americana', 'American Samoa', 'AS', 'ASM', '1 684');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Bartolomé', 'Saint Barthélemy', 'BL', 'BLM', '590');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Cristóbal y Nieves', 'Saint Kitts and Nevis', 'KN', 'KNA', '1 869');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Marino', 'San Marino', 'SM', 'SMR', '378');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Martín (Francia)', 'Saint Martin (French part)', 'MF', 'MAF', '1 599');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Pedro y Miquelón', 'Saint Pierre and Miquelon', 'PM', 'SPM', '508');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('San Vicente y las Granadinas', 'Saint Vincent and the Grenadines', 'VC', 'VCT', '1 784');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Santa Elena', 'Ascensión y Tristán de Acuña', 'SH', 'SHN', '290');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Santa Lucía', 'Saint Lucia', 'LC', 'LCA', '1 758');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Santo Tomé y Príncipe', 'Sao Tome and Principe', 'ST', 'STP', '239');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Senegal', 'Senegal', 'SN', 'SEN', '221');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Serbia', 'Serbia', 'RS', 'SRB', '381');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Seychelles', 'Seychelles', 'SC', 'SYC', '248');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sierra Leona', 'Sierra Leone', 'SL', 'SLE', '232');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Singapur', 'Singapore', 'SG', 'SGP', '65');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sint Maarten', 'Sint Maarten', 'SX', 'SMX', '1 721');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Siria', 'Syria', 'SY', 'SYR', '963');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Somalia', 'Somalia', 'SO', 'SOM', '252');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sri lanka', 'Sri Lanka', 'LK', 'LKA', '94');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sudáfrica', 'South Africa', 'ZA', 'ZAF', '27');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Sudán', 'Sudan', 'SD', 'SDN', '249');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Suecia', 'Sweden', 'SE', 'SWE', '46');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Suiza', 'Switzerland', 'CH', 'CHE', '41');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Surinám', 'Suriname', 'SR', 'SUR', '597');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Svalbard y Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM', '47');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Swazilandia', 'Swaziland', 'SZ', 'SWZ', '268');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tayikistán', 'Tajikistan', 'TJ', 'TJK', '992');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tailandia', 'Thailand', 'TH', 'THA', '66');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Taiwán', 'Taiwan', 'TW', 'TWN', '886');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tanzania', 'Tanzania', 'TZ', 'TZA', '255');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Territorio Británico del Océano Índico', 'British Indian Ocean Territory', 'IO', 'IOT', '246');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Territorios Australes y Antárticas Franceses', 'French Southern Territories', 'TF', 'ATF', 'nan');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Timor Oriental', 'East Timor', 'TL', 'TLS', '670');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Togo', 'Togo', 'TG', 'TGO', '228');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tokelau', 'Tokelau', 'TK', 'TKL', '690');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tonga', 'Tonga', 'TO', 'TON', '676');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Trinidad y Tobago', 'Trinidad and Tobago', 'TT', 'TTO', '1 868');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tunez', 'Tunisia', 'TN', 'TUN', '216');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Turkmenistán', 'Turkmenistan', 'TM', 'TKM', '993');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Turquía', 'Turkey', 'TR', 'TUR', '90');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Tuvalu', 'Tuvalu', 'TV', 'TUV', '688');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Ucrania', 'Ukraine', 'UA', 'UKR', '380');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Uganda', 'Uganda', 'UG', 'UGA', '256');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Uruguay', 'Uruguay', 'UY', 'URY', '598');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Uzbekistán', 'Uzbekistan', 'UZ', 'UZB', '998');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Vanuatu', 'Vanuatu', 'VU', 'VUT', '678');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Venezuela', 'Venezuela', 'VE', 'VEN', '58');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Vietnam', 'Vietnam', 'VN', 'VNM', '84');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Wallis y Futuna', 'Wallis and Futuna', 'WF', 'WLF', '681');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Yemen', 'Yemen', 'YE', 'YEM', '967');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Yibuti', 'Djibouti', 'DJ', 'DJI', '253');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Zambia', 'Zambia', 'ZM', 'ZMB', '260');
INSERT INTO countries (nombre, name, iso2, iso3, phone_code) VALUES ('Zimbabue', 'Zimbabwe', 'ZW', 'ZWE', '263');